disabled_rules:
opt_in_rules:
  - attributes
  - closure_spacing
  - empty_count
  - fatal_error_message
  - implicitly_unwrapped_optional
  - multiline_parameters
  - operator_usage_whitespace
included:
  - Sources
  - Tests
excluded:

line_length:
  warning: 200
  error: 250

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length: 2
  max_lenght:
    warning: 20
    error: 40

type_name:
  min_length: 3
  max_lenght:
    warning: 50
    error: 60

function_body_length:
  warning: 50
  error: 100

force_cast: error
force_try: error 