language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode8.3

before_install:
  - gem install xcpretty
  - gem install scan

script:
  - fastlane scan

after_success:
  - bash <(curl -s https://codecov.io/bash)
