language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode7.3

before_install:
  - gem install xcpretty
  - gem install scan

before_script:
 - carthage bootstrap --platform iOS

script:
  - scan

after_success:
  - bash <(curl -s https://codecov.io/bash)
