language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode7.3

before_install:
  - gem install xcpretty

before_script:
 - carthage bootstrap --platform iOS

script:
  - xcodebuild test -project iTunesSearchAPI.xcodeproj -scheme "iTunesSearchAPI-iOS" -sdk iphonesimulator

after_success:
  - bash <(curl -s https://codecov.io/bash)
