language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode7.3

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- gem install xcpretty
- brew update
- brew install carthage

before_script:
  - carthage bootstrap

script:
- xcodebuild test -workspace iTunesSearchAPI.xcworkspace -scheme "iTunesSearchAPI-iOS" -sdk iphonesimulator

after_success:
  - bash <(curl -s https://codecov.io/bash)
