fastlane_version "2.3.0"

opt_out_usage

default_platform :ios

platform :ios do
    lane :test do
        scan(project: "iTunesSearchAPI.xcodeproj", scheme: "iTunesSearchAPI-tvOS", code_coverage: false)
        scan(project: "iTunesSearchAPI.xcodeproj", scheme: "iTunesSearchAPI-iOS", code_coverage: true)
    end
end
