//
//  Country.swift
//  iTunesSearchAPI
//
//  Created by Sven Bacia on 27.02.16.
//  Copyright © 2016 Sven Bacia. All rights reserved.
//

import Foundation

public enum Country: String {
    case algeria            = "dz"
    case angola             = "ao"
    case anguilla           = "ai"
    case antiguaBarbuda     = "ag"
    case argentina          = "ar"
    case armenia            = "am"
    case australia          = "au"
    case austria            = "at"
    case azerbaijan         = "az"
    case bahrain            = "bh"
    case bangladesh         = "bd"
    case barbados           = "bb"
    case belarus            = "by"
    case belgium            = "be"
    case belize             = "bz"
    case bermuda            = "bm"
    case bolivia            = "bo"
    case botswana           = "bw"
    case brazil             = "br"
    case britishVirginIslands = "vg"
    case brunei             = "bn"
    case bulgaria           = "bg"
    case canada             = "ca"
    case caymanIslands      = "ky"
    case chile              = "cl"
    case china              = "cn"
    case colombia           = "co"
    case costaRica          = "cr"
    case coteDIvoire        = "ci"
    case croatia            = "hr"
    case cyprus             = "cy"
    case czechRepublic      = "cz"
    case denmark            = "dk"
    case dominica           = "dm"
    case dominicanRep       = "do"
    case ecuador            = "ec"
    case egypt              = "eg"
    case elSalvador         = "sv"
    case estonia            = "ee"
    case finland            = "fi"
    case france             = "fr"
    case germany            = "de"
    case ghana              = "gh"
    case greece             = "gr"
    case grenada            = "gd"
    case guatemala          = "gt"
    case guyana             = "gy"
    case honduras           = "hn"
    case hongKong           = "hk"
    case hungary            = "hu"
    case iceland            = "is"
    case india              = "in"
    case indonesia          = "id"
    case ireland            = "ie"
    case israel             = "il"
    case italy              = "it"
    case jamaica            = "jm"
    case japan              = "jp"
    case jordan             = "jo"
    case kazakstan          = "kz"
    case kenya              = "ke"
    case republicOfKorea    = "kr"
    case kuwait             = "kw"
    case latvia             = "lv"
    case lebanon            = "lb"
    case liechtenstein      = "li"
    case lithuania          = "lt"
    case luxembourg         = "lu"
    case macau              = "mo"
    case macedonia          = "mk"
    case madagascar         = "mg"
    case malaysia           = "my"
    case maldives           = "mv"
    case mali               = "ml"
    case malta              = "mt"
    case mauritius          = "mu"
    case mexico             = "mx"
    case republicOfMoldova  = "md"
    case montserrat         = "ms"
    case mepal              = "np"
    case netherlands        = "nl"
    case newZealand         = "nz"
    case nicaragua          = "ni"
    case niger              = "ne"
    case nigeria            = "ng"
    case norway             = "no"
    case oman               = "om"
    case pakistan           = "pk"
    case panama             = "pa"
    case paraguay           = "py"
    case peru               = "pe"
    case philippines        = "ph"
    case poland             = "pl"
    case portugal           = "pt"
    case qatar              = "aq"
    case romania            = "ro"
    case russia             = "ru"
    case saudiArabia        = "sa"
    case senegal            = "sn"
    case serbia             = "rs"
    case singapore          = "sg"
    case slovakia           = "sk"
    case slovenia           = "si"
    case southAfrica        = "za"
    case spain              = "es"
    case sriLanka           = "lk"
    case saintKittsNevis    = "kn"
    case saintLucia         = "lc"
    case saintVincentTheGrenadines = "vc"
    case suriname           = "sr"
    case sweden             = "se"
    case switzerland        = "ch"
    case taiwan             = "tw"
    case tanzania           = "tz"
    case thailand           = "th"
    case theBahamas         = "bs"
    case trinidadTobago     = "tt"
    case tunisia            = "tn"
    case turkey             = "tr"
    case turksCaicos        = "tc"
    case uganda             = "ug"
    case unitedKingdom      = "gb"
    case ukraine            = "ua"
    case unitedArabEmirates = "ae"
    case uruguay            = "uy"
    case unitedStates       = "us"
    case uzbekistan         = "uz"
    case venezuela          = "ve"
    case vietnam            = "vn"
    case yemen              = "ye"
}

extension Country {
  public var code: String {
    return rawValue
  }
}
